### ISSUE TITLE
flatpak repo gpg key is missing

### ISSUE THREAD

**Issue by AdamIsrael** [castrojo/ublue#25]
There are some edge cases where a flatpak repo is added but fails to add the repos GPG key, in which case installing from the repo fails.

In one case, this happens when you opt to include 3rd party repositories during installation. This seems to add the flathub repo but not its GPG key.

We detect when the GPG is missing and fail fast, but the proper fix is to remove the flatpak repo so that, when the 00 script is re-run, it can re-add the repo and the GPG key.

**Comment by superuser-miguel** [comment]
Not sure if this is much help, but Fedora has a filter for the 3rd Party Repo slider when you first install Silverblue. The Flathub repo is added, allowing 6 apps through (MS Teams, Skype, Minecraft, Zoom, BitWarden, Postman) but to fully enable the Flathub repo, you need to add it again. The filter denies all, then allows the 6 through. I believe this breaks search as well but that's out of scope here. [Here is a link to the filter.](https://pagure.io/fedora-flathub-filter/blob/main/f/fedora-flathub.filter)

**Comment by castrojo** [comment]
`flatpak remote-modify --enable flathub` seems to fix all of this so I've added it to the script and I've tested it a bunch and reasonably certain this is fixed, please reopen if you see again!
