### ISSUE TITLE
Add an ostree remote for ublue

### ISSUE THREAD

**Issue by mjcc30** [castrojo/ublue#47]
Hello,
I use ublue on my daily laptop since 4 month and its work peferctly,
so i'm asking you if it's possible to make an ostree remote like thoose projects ? 
https://github.com/martinpitt/ostree-pitti-workstation
https://github.com/VinnyVynce/silvernobara

unfortunately I can't make it work, if you have an idea or if you can make a video on it that would be great!
thank you!

**Comment by castrojo** [comment]
Yeah I'd love to do this, but it's above my current skill level, perhaps someday, I'll keep this open!

**Comment by castrojo** [comment]
OK here's the long term plan: https://fedoraproject.org/wiki/Changes/OstreeNativeContainerStable

Then this'll just be a Dockerfile and I'll build images on github.

**Comment by castrojo** [comment]
OK, doing it, it's working well so far but still needs some baking/testing: https://github.com/castrojo/ublue-image
